version: '3'
networks:
  grap-network:
    driver: bridge

services:
  server:
    build:
      context: .
      dockerfile: dev.Dockerfile
    user: $currentUser:$currentGroup
    image: grap-backend
    container_name: grap-backend
    command: sh -c "[ ! -d node_modules ] && npm i; npm run dev"
    # command: tail -F /dev/null
    volumes:
      - ../server:/app
      - ../database-volume:/database-volume
    ports:
      - 3000:3000
      - 25:25
    networks:
      - grap-network
