name: Pull request pipeline

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Setup and run tests
        working-directory: /app
        run: |
          cd server
          npm install
          npm run lint
          npm run build
          npm test
        env:
          NODE_ENV: test
          DATABASE_PATH: /database-volume/database.sqlite
          SESSION_SECRET: i-hope-you-update-me-on-prod-i-need-to-be-at-least-32-chars
          DOMAIN: grap.email
