name: Pull request pipeline

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: cd server
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm test
