name: Release build

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: server
          file: .docker/prod.Dockerfile
          sbom: true # https://docs.docker.com/build/ci/github-actions/attestations/
          provenance: mode=max
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/grap:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/grap:${{ github.ref_name }}
